GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/6213725f0e2c17739fa01828

###

Post http://localhost:3000/subscribers
Content-Type: application/json

{
"name": "Dragon ball ",
"subscribedToChannel": "Web Dev Simplified"
}

###

DELETE http://localhost:3000/subscribers/621365eb0e2c17739fa01826

###

PATCH http://localhost:3000/subscribers/621381781613325044f9d673
Content-Type: application/json

{
    "name": "Dragon ball z"
}